### ISSUE TITLE
make fails on macOS 10.13.6

### ISSUE THREAD

**Issue by mohammed-ali-1** [SystemsApproach/book#9]
When trying to run `make` to build a web version of the book, the following error is generated:
```

runTopLevelLifecycles → 2 ▄ ╢█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████░░░░░╟
internal/child_process.js:323
    throw errnoException(err, 'spawn');
    ^

Error: spawn E2BIG
    at _errnoException (util.js:992:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at exports.spawn (child_process.js:502:9)
    at spawn (/Users/mohammedalameen/.gitbook/versions/3.2.3/node_modules/npm/lib/utils/spawn.js:7:13)
    at runCmd_ (/Users/mohammedalameen/.gitbook/versions/3.2.3/node_modules/npm/lib/utils/lifecycle.js:237:14)
    at runCmd (/Users/mohammedalameen/.gitbook/versions/3.2.3/node_modules/npm/lib/utils/lifecycle.js:196:5)
    at runPackageLifecycle (/Users/mohammedalameen/.gitbook/versions/3.2.3/node_modules/npm/lib/utils/lifecycle.js:160:3)
    at Array.<anonymous> (/Users/mohammedalameen/.gitbook/versions/3.2.3/node_modules/npm/node_modules/slide/lib/bind-actor.js:15:8)
    at LOOP (/Users/mohammedalameen/.gitbook/versions/3.2.3/node_modules/npm/node_modules/slide/lib/chain.js:15:14)
    at chain (/Users/mohammedalameen/.gitbook/versions/3.2.3/node_modules/npm/node_modules/slide/lib/chain.js:20:5)
make: *** [setup] Error 1
```

**Comment by llpeterson** [comment]
This is a known issue (see `status.md`). A work-around is to run `make` a second time. A better fix would be appreciated.
